### ISSUE TITLE
Create HUD overlay

### ISSUE THREAD

**Issue by grant-m-s** [CosyClub/ProjectTempo#83] opened 2018-03-08 17:20 UTC

**Comment by qqii** [comment] 2018-03-21 16:05
Duplicate of #25?

**Comment by jnterry** [comment] 2018-03-22 14:21
@Codrin-Popa has told @AnthonyWharton to do this in the next day or so

**Comment by grant-m-s** [comment] 2018-04-12 10:14
#141 will be complete soon

**Closed** 2018-04-18 22:28 UTC
Labels: enhancement
